### ISSUE TITLE
Laminar flow past cylinder

### ISSUE THREAD

**Issue by samiit** [Comflics/Exploring-OpenFOAM#2]
Hello,

Thank you for the case with attempts at validation with literature. I see that you are simulating for Re=100, yet your nu = 0.02. Besides, in your controlDict, I find that your Aref = 2 and rhoInf = 1.225

How does this fulfil the condition for Re=100? Besides, how does this account for the lift and drag coefficient evaluations?

Thanks,

Sam

**Comment by sadiqhuq** [comment]
Hi Sam,
Re = rho * U * L / mu
where, mu = rho * nu
Re = U * L / nu = 1 * 2 / 0.02 = 100
Cheers,
Sadiq

**Comment by sadiqhuq** [comment]
Please refer to Exploring OpenFOAM PDF for force coefficients.

**Comment by samiit** [comment]
Hi Sadiq,
Thank you for your prompt response.
In your [controlDict,](https://github.com/Comflics/Exploring-OpenFOAM/blob/master/laminarVortexShedding/system/controlDict) the `lRef` value **is 1** and _not 2_, so Re would turn out to be 200.
I checked the force coefficients as in your description, also in the [code documentation](https://cpp.openfoam.org/v4/a06430_source.html), and it is here that Aref is used.

Sam

**Comment by sadiqhuq** [comment]
Hi again,
Re_d = U * D / nu  (Should have not used L earlier). For cylinder case it's common to calculate Reynold's number with Diameter as the charachteristic length. Btw 1x1 / 0.02 = 50 :)
In case of an airfoil it's common to use chord length for the forces. Whereas in the case of a 2D cylinder,  the refernce area (ARef) is the diameter and this value is used for calculating Cd and Cl. lRef is needed only for Cm, as you can see in the link that you sent.

**Comment by samiit** [comment]
Vanakam Sadiq,

Thanks for your answer and your gentle correction. At least it is a Re=50 case!
Besides, I understand that Aref is the projected area, so it should be D x Z, where Z is the depth of the 2D mesh. I considered it in my simulations and am able to validate **Cd** & **Cl** with the literature value, although not the **St** yet!

As you might notice in the [code documentation](https://cpp.openfoam.org/v4/a06430_source.html), for evaluation of **Cd** and **Cl**, there is a `pDyn` term which is calculated using `rhoRef_`, so I'm not sure why you've taken it to be 1.225 (as in your controlDict).

Sam

**Comment by sadiqhuq** [comment]
Vanakkam Sam,

Your understanding of Cd and Cl is correct. I have added a python code (strouhal.py) to do fft, take a look.

The incompressible solvers in OF use kinematic pressure (i.e p/rho). But we need dynamic pressure to compute Cd, therefore a rhoInf need to be specified. The value for rhoInf and nu are arbitarily chosen to give the Re we want for the tested velocity and cylinder diameter. 

I'm citing OF-2.3.x, there are some re-arrangement of the code in the later versions: ["Return rho if rhoName is specified otherwise rhoRef"](https://github.com/OpenFOAM/OpenFOAM-2.3.x/blob/master/src/postProcessing/functionObjects/forces/forces/forces.H#L247). 

The formula for drag:
Cd = Fd / (0.5 * rhoInf * UInf^2 * A)
pDyn = 0.5 * rhoInf * UInf^2
Cd = Fd / (pDyn * A )
Fd = (totForce & dragDir_)   
Where, the & is the dot product operator,
